"""
Module 3 - Procurement Management: SQLAlchemy Models
Tables: procurement_requests, procurement_approvals, purchase_orders,
        procurement_status_history, order_tracking, invoices
"""
import enum
from sqlalchemy import (
    Column, Integer, String, Enum, ForeignKey,
    DateTime, Text, Numeric, Date
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base


# ---------------------------------------------------------------------------
# Python / DB Enums
# ---------------------------------------------------------------------------

class ProcurementPriority(str, enum.Enum):
    LOW      = "Low"
    MEDIUM   = "Medium"
    HIGH     = "High"
    CRITICAL = "Critical"


class ProcurementStatus(str, enum.Enum):
    PENDING   = "Pending"
    APPROVED  = "Approved"
    ORDERED   = "Ordered"
    DELIVERED = "Delivered"
    COMPLETED = "Completed"
    CANCELLED = "Cancelled"


class ApprovalStatus(str, enum.Enum):
    APPROVED  = "Approved"
    REJECTED  = "Rejected"
    SENT_BACK = "Sent Back"


class DeliveryStatus(str, enum.Enum):
    AWAITING_SHIPMENT = "Awaiting Shipment"
    IN_TRANSIT        = "In Transit"
    DELIVERED         = "Delivered"
    DELAYED           = "Delayed"
    COMPLETED         = "Completed"


class PaymentStatus(str, enum.Enum):
    PENDING  = "Pending"
    VERIFIED = "Verified"
    APPROVED = "Approved"
    PAID     = "Paid"
    REJECTED = "Rejected"


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

class ProcurementRequest(Base):
    """
    Central procurement request raised by any authorised user.
    request_number is auto-generated by the service layer (PR-YYYY-XXXX).
    """
    __tablename__ = "procurement_requests"

    id                    = Column(Integer, primary_key=True, index=True)
    request_number        = Column(String(20), unique=True, nullable=False, index=True)  # PR-YYYY-XXXX
    request_title         = Column(String(255), nullable=False)
    department_name       = Column(String(150), nullable=False)
    requested_by          = Column(Integer, ForeignKey("users.id"), nullable=False)

    # Item details
    item_name             = Column(String(255), nullable=False)
    product_category      = Column(String(150), nullable=False)
    quantity              = Column(Numeric(12, 3), nullable=False)
    unit_of_measurement   = Column(String(50), nullable=False)
    estimated_budget      = Column(Numeric(15, 2), nullable=False)
    required_delivery_date = Column(Date, nullable=False)

    priority              = Column(Enum(ProcurementPriority), nullable=False,
                                   default=ProcurementPriority.MEDIUM)
    business_justification = Column(Text, nullable=False)
    additional_remarks    = Column(Text, nullable=True)
    supporting_document_url = Column(String(500), nullable=True)

    status                = Column(Enum(ProcurementStatus), nullable=False,
                                   default=ProcurementStatus.PENDING)
    assigned_vendor_id    = Column(Integer, ForeignKey("vendors.id"), nullable=True)

    created_at            = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at            = Column(DateTime(timezone=True), onupdate=func.now(), nullable=True)

    # Relationships
    requester             = relationship("User",   foreign_keys=[requested_by])
    assigned_vendor       = relationship("Vendor", foreign_keys=[assigned_vendor_id])
    approvals             = relationship("ProcurementApproval",  back_populates="request",
                                        cascade="all, delete-orphan")
    purchase_order        = relationship("PurchaseOrder",        back_populates="request",
                                        uselist=False)
    status_history        = relationship("ProcurementStatusHistory", back_populates="request",
                                        cascade="all, delete-orphan")


class ProcurementApproval(Base):
    """
    Records each approval/rejection/send-back action on a procurement request.
    """
    __tablename__ = "procurement_approvals"

    id              = Column(Integer, primary_key=True, index=True)
    request_id      = Column(Integer, ForeignKey("procurement_requests.id"), nullable=False)
    approval_status = Column(Enum(ApprovalStatus), nullable=False)
    approved_by     = Column(Integer, ForeignKey("users.id"), nullable=False)
    approval_date   = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    remarks         = Column(Text, nullable=True)

    request         = relationship("ProcurementRequest", back_populates="approvals")
    approver        = relationship("User", foreign_keys=[approved_by])


class PurchaseOrder(Base):
    """
    One-to-one with ProcurementRequest; created after approval.
    po_number is auto-generated by the service layer (PO-YYYY-XXXX).
    """
    __tablename__ = "purchase_orders"

    id                    = Column(Integer, primary_key=True, index=True)
    po_number             = Column(String(20), unique=True, nullable=False, index=True)  # PO-YYYY-XXXX
    request_id            = Column(Integer, ForeignKey("procurement_requests.id"),
                                   unique=True, nullable=False)
    vendor_id             = Column(Integer, ForeignKey("vendors.id"), nullable=False)

    product_details       = Column(Text, nullable=False)
    quantity_ordered      = Column(Numeric(12, 3), nullable=False)
    unit_price            = Column(Numeric(15, 2), nullable=False)
    total_cost            = Column(Numeric(17, 2), nullable=False)
    tax_details           = Column(Text, nullable=True)
    shipping_address      = Column(Text, nullable=True)
    expected_delivery_date = Column(Date, nullable=True)
    payment_terms         = Column(String(100), nullable=True, default="Net 30")
    po_status             = Column(String(50), nullable=False, default="Draft")

    approved_by           = Column(Integer, ForeignKey("users.id"), nullable=True)
    po_date               = Column(Date, nullable=True)
    created_at            = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    request               = relationship("ProcurementRequest", back_populates="purchase_order")
    vendor                = relationship("Vendor",             foreign_keys=[vendor_id])
    approver              = relationship("User",               foreign_keys=[approved_by])
    order_tracking        = relationship("OrderTracking",      back_populates="purchase_order",
                                        uselist=False, cascade="all, delete-orphan")
    invoices              = relationship("Invoice",            back_populates="purchase_order",
                                        cascade="all, delete-orphan")


class ProcurementStatusHistory(Base):
    """
    Immutable audit trail every time a ProcurementRequest changes status.
    """
    __tablename__ = "procurement_status_history"

    id          = Column(Integer, primary_key=True, index=True)
    request_id  = Column(Integer, ForeignKey("procurement_requests.id"), nullable=False)
    old_status  = Column(String(50), nullable=True)   # nullable for initial creation
    new_status  = Column(String(50), nullable=False)
    changed_by  = Column(Integer, ForeignKey("users.id"), nullable=False)
    changed_at  = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    remarks     = Column(Text, nullable=True)

    request     = relationship("ProcurementRequest", back_populates="status_history")
    changed_by_user = relationship("User", foreign_keys=[changed_by])


class OrderTracking(Base):
    """
    Shipment / delivery tracking for a PurchaseOrder.
    delay_days is a computed column derived in the service layer (not stored redundantly).
    """
    __tablename__ = "order_tracking"

    id                    = Column(Integer, primary_key=True, index=True)
    po_id                 = Column(Integer, ForeignKey("purchase_orders.id"),
                                   unique=True, nullable=False)
    dispatch_date         = Column(Date, nullable=True)
    expected_delivery_date = Column(Date, nullable=True)
    actual_delivery_date  = Column(Date, nullable=True)
    delivery_status       = Column(Enum(DeliveryStatus), nullable=False,
                                   default=DeliveryStatus.AWAITING_SHIPMENT)
    delay_days            = Column(Integer, nullable=True)   # computed & persisted on update
    remarks               = Column(Text, nullable=True)
    updated_at            = Column(DateTime(timezone=True), server_default=func.now(),
                                   onupdate=func.now(), nullable=False)

    purchase_order        = relationship("PurchaseOrder", back_populates="order_tracking")


class Invoice(Base):
    """
    One PO can have multiple invoices (partial invoicing / progress billing).
    """
    __tablename__ = "invoices"

    id                  = Column(Integer, primary_key=True, index=True)
    invoice_number      = Column(String(50), unique=True, nullable=False, index=True)
    po_id               = Column(Integer, ForeignKey("purchase_orders.id"), nullable=False)
    vendor_id           = Column(Integer, ForeignKey("vendors.id"), nullable=False)

    invoice_date        = Column(Date, nullable=False)
    invoice_amount      = Column(Numeric(15, 2), nullable=False)
    tax_amount          = Column(Numeric(15, 2), nullable=True, default=0)
    total_amount        = Column(Numeric(15, 2), nullable=False)
    due_date            = Column(Date, nullable=True)

    payment_status      = Column(Enum(PaymentStatus), nullable=False,
                                 default=PaymentStatus.PENDING)
    invoice_document_url = Column(String(500), nullable=True)
    verified_by         = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at          = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    purchase_order      = relationship("PurchaseOrder", back_populates="invoices")
    vendor              = relationship("Vendor",        foreign_keys=[vendor_id])
    verifier            = relationship("User",          foreign_keys=[verified_by])
