import * as XLSX from 'xlsx';
import type {
  ReportType, ReportFilters,
  VendorPerformanceReportResult, ProcurementReportResult,
  PurchaseOrderReportResult, ComplianceReportResult,
  ContractReportResult, ExecutiveSummaryReportResult,
} from '../models/report';

type AnyReportResult =
  | VendorPerformanceReportResult | ProcurementReportResult
  | PurchaseOrderReportResult     | ComplianceReportResult
  | ContractReportResult          | ExecutiveSummaryReportResult;

function getFilename(reportType: string): string {
  const dateStr = new Date().toISOString().split('T')[0];
  const typeMap: Record<string, string> = {
    'vendor-performance': 'Vendor_Performance_Report',
    'procurement': 'Procurement_Report',
    'purchase-order': 'Purchase_Order_Report',
    'compliance': 'Compliance_Report',
    'contract': 'Contract_Report',
    'executive-summary': 'Executive_Summary_Report',
  };
  const prefix = typeMap[reportType] ?? 'VendorIQ_Report';
  return `${prefix}_${dateStr}.xlsx`;
}

function autoFitColumns(worksheet: XLSX.WorkSheet, data: Record<string, unknown>[]) {
  if (!data.length) return;
  const colKeys = Object.keys(data[0]);
  worksheet['!cols'] = colKeys.map(key => {
    let maxLen = key.length;
    data.forEach(row => {
      const val = row[key];
      if (val !== null && val !== undefined) {
        const len = String(val).length;
        if (len > maxLen) maxLen = len;
      }
    });
    return { wch: Math.min(Math.max(maxLen + 4, 12), 40) };
  });
}

export function exportReportToExcel(
  reportType: ReportType,
  reportTitle: string,
  filters: ReportFilters,
  result: AnyReportResult,
  userName: string = 'System User'
): string {
  const wb = XLSX.utils.book_new();
  const dateStr = new Date().toLocaleString('en-IN');

  // Sheet 1: Summary Info
  const summaryRows: (string | number)[][] = [
    ['REPORT SUMMARY'],
    ['Title', reportTitle],
    ['Report Type', reportType],
    ['Generated Date', dateStr],
    ['Generated By', userName],
    ['Date Range', `${filters.startDate || 'N/A'} to ${filters.endDate || 'N/A'}`],
    ['Category Filter', filters.vendorCategory || 'All'],
    ['Department Filter', filters.departments?.join(', ') || 'All'],
    ['Record Count', result.meta.recordCount],
    [],
    ['KPI METRICS'],
  ];

  // Populate KPIs based on report type
  if (reportType === 'vendor-performance') {
    const res = result as VendorPerformanceReportResult;
    summaryRows.push(
      ['Total Vendors Evaluated', res.summary.totalVendors],
      ['Avg On-Time Delivery %', `${res.summary.onTimeDeliveryAvg}%`],
      ['Avg Quality Score', res.summary.avgQualityScore],
      ['High Risk Vendor Count', res.summary.highRiskCount]
    );
  } else if (reportType === 'procurement') {
    const res = result as ProcurementReportResult;
    summaryRows.push(
      ['Total Requests', res.summary.totalRequests],
      ['Approved Count', res.summary.approvedCount],
      ['Completed Count', res.summary.completedCount],
      ['Avg Processing Days', `${res.summary.avgProcessingDays} days`],
      ['Total Estimated Spend', res.summary.totalBudget]
    );
  } else if (reportType === 'purchase-order') {
    const res = result as PurchaseOrderReportResult;
    summaryRows.push(
      ['Total POs', res.summary.totalPOs],
      ['Total Order Value', res.summary.totalValue],
      ['Fulfilled Count', res.summary.fulfilledCount],
      ['Delayed Count', res.summary.delayedCount],
      ['Pending Payment Value', res.summary.pendingPaymentValue]
    );
  } else if (reportType === 'compliance') {
    const res = result as ComplianceReportResult;
    summaryRows.push(
      ['Overall Compliance Rate', `${res.summary.complianceRate}%`],
      ['Total Vendors', res.summary.totalVendors],
      ['Fully Compliant Vendors', res.summary.compliantVendors],
      ['Expired Certifications', res.summary.expiredCount],
      ['Pending Verifications', res.summary.pendingCount]
    );
  } else if (reportType === 'contract') {
    const res = result as ContractReportResult;
    summaryRows.push(
      ['Total Contracts', res.summary.totalContracts],
      ['Active Contracts', res.summary.activeCount],
      ['Total Portfolio Value', res.summary.totalValue],
      ['Expiring in 30 Days', res.summary.expiringIn30Days],
      ['Renewal Rate %', `${res.summary.renewalRate}%`]
    );
  } else if (reportType === 'executive-summary') {
    const res = result as ExecutiveSummaryReportResult;
    summaryRows.push(
      ['Active Vendors', res.vendorKPIs.activeVendors],
      ['Total Procurement Spend', res.poKPIs.totalSpend],
      ['Overall Compliance %', `${res.complianceKPIs.overallComplianceRate}%`],
      ['Contracts Expiring (30d)', res.contractKPIs.expiringIn30Days]
    );
  }

  // Insights section in summary
  summaryRows.push([], ['KEY INSIGHTS']);
  result.insights.forEach(ins => summaryRows.push(['• ' + ins]));

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryRows);
  XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary');

  // Data sheets
  if (reportType === 'executive-summary') {
    const res = result as ExecutiveSummaryReportResult;
    
    const vendorSheet = XLSX.utils.json_to_sheet(res.topVendors);
    autoFitColumns(vendorSheet, res.topVendors as unknown as Record<string, unknown>[]);
    XLSX.utils.book_append_sheet(wb, vendorSheet, 'Top Vendors');

    const riskSheet = XLSX.utils.json_to_sheet(res.riskSummary);
    autoFitColumns(riskSheet, res.riskSummary as unknown as Record<string, unknown>[]);
    XLSX.utils.book_append_sheet(wb, riskSheet, 'Risk Breakdown');

    const trendSheet = XLSX.utils.json_to_sheet(res.monthlyTrend);
    autoFitColumns(trendSheet, res.monthlyTrend as unknown as Record<string, unknown>[]);
    XLSX.utils.book_append_sheet(wb, trendSheet, 'Monthly Trends');
  } else {
    // Standard data rows table
    let dataRows: Record<string, unknown>[] = [];
    if (reportType === 'vendor-performance') {
      dataRows = (result as VendorPerformanceReportResult).rows as unknown as Record<string, unknown>[];
    } else if (reportType === 'procurement') {
      dataRows = (result as ProcurementReportResult).byDepartment as unknown as Record<string, unknown>[];
    } else if (reportType === 'purchase-order') {
      dataRows = (result as PurchaseOrderReportResult).rows as unknown as Record<string, unknown>[];
    } else if (reportType === 'compliance') {
      dataRows = (result as ComplianceReportResult).byVendor as unknown as Record<string, unknown>[];
    } else if (reportType === 'contract') {
      dataRows = (result as ContractReportResult).rows as unknown as Record<string, unknown>[];
    }

    if (dataRows.length > 0) {
      const dataSheet = XLSX.utils.json_to_sheet(dataRows);
      autoFitColumns(dataSheet, dataRows);
      XLSX.utils.book_append_sheet(wb, dataSheet, 'Detailed Data');
    }
  }

  const filename = getFilename(reportType);
  XLSX.writeFile(wb, filename);
  return filename;
}
